---
title: "Curriculum Development Officer - Data Science"
subtitle: "How can rural workers be supported to develop skills in Data Science? Why do they need these skills?"
author: "Andrew Duncan"
date: "16/09/2019"
output:
  xaringan::moon_reader:
    css: [default, chocolate, chocolate-fonts, "xaringan_css/chocolate_custom.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: center, middle

# Why, What and How


???
Good afternoon. Today I'm going to hopefully answer the two questions in the title here "How can rural workers be supported to develop skills in Data Science" and "Why do they need these skills"

I will begin by discussing why they need these skills, then I will outline what some of these skills might be because the skills that someone needs to develop will influence how they need to be supported in developing them.

---
class: inverse, center, middle

# Why?

???
So, let me begin with why rural workers need Data Science skills
---
# Why do Rural Workers need Data Science Skills?

.left-column[
### Why?
]


.right-column[

- Scottish Government have identified a need

> "With partners, we will develop a programme to help rural businesses access all the digital support currently available to enable them to up skill and expand."

> --- Programme for Scotland 2019 - 2020

]

???
First, I might suggest that there are many workers across the country that need to develop data science skills and that would include rural workers. 

Regardless of this the Scottish Government, in their Programme for Scotland, have identified a specific need to help rural businesses up skill. They also make clear the contributions that the life sciences sector make with regard to big data. 
---
# Why do Rural Workers need Data Science Skills?

.left-column[
### Why?
]


.right-column[

- Scottish Government have identified a need

- Highlands and Islands Enterprise [Growth Sectors](http://www.hie.co.uk/growth-sectors/) all need data science skills 

    - Energy
    
    - Life Sciences
    
    - Food and Drink
    
    - Creative Industries
    
    - Tourism
    
    - Business Services
    
    - Universities

]

???
Highlands and Islands Enterprise (or HIE) have identified 7 growth sectors in our area of the country, including life sciences, and all of these growth sectors could benefit from data science skills. Whether that be in analysing tourist numbers to predict foot fall or scrapping twitter and facebook to help the creative industries or upskilling businesses with regard to human resources data. 
---
# Why do Rural Workers need Data Science Skills?

.left-column[
### Why?
]


.right-column[

- Scottish Government have identified a need.

- Highlands and Islands Enterprise [Growth Sectors](http://www.hie.co.uk/growth-sectors/) all need data science skills. 

- Difficult to attract skilled workers to Highlands and Islands.

]

???
However, many business find it difficult to attract skilled workers to the Highlands and Islands - particularly to those businesses outside Inverness. It may well be that upskilling existing employees is going to be more viable for businesses than finding recruits with those skills that want to work in the Highlands and Islands. 

---
class: inverse, center, middle

# What?

???
Having considered why rural workers might need data science skills, we should consider what these skills might be. 
---
# What skills do they need?

.left-column[
### Why?

### What?
]

.right-column[

- Skills will define tools required to teach them

- Ethics

- Interpretation

]

???
The reason for this is that the skills required will define the tools needed to teach them. For example teaching Ethics (or GDPR) or Interpretation of results might require discussion amongst students or material for them to read or watch but it might not require data itself or additional computational software.
---
# What skills do they need?

.left-column[
### Why?

### What?
]

.right-column[

- Skills will define tools required to teach them

- Ethics

- Interpretation

- Computational skills: *R*, *GIS*, *Python*

]

???
But data science is synonymous with computational skills using some form of programming language or advanced software and for this we may need to use some different tools. 
---
# What skills do they need?

.left-column[
### Why?

### What?
]

.right-column[

- Skills will define tools required to teach them

- Ethics

- Interpretation

- Computational skills: *R*, *GIS*, *Python*

- Accessing training face to face difficult - remote teaching. 

]

???
Finally, we need to consider that accessing face to face training may be very difficult be that financial or transport or time related difficulties and so traditional classroom teaching may not suffice.
---
class: inverse, center, middle

# How?

--

## Using existing Web Technologies

???
So how do we go about helping rural workers develop data science skills. Well we can use existing web technologies - either those that are available already within UHI or others that could be.

---
# Existing Web Technologies

.left-column[
### Why?

### What?

### How?
]

.right-column[
- Brightspace

- Video Conferencing

- Bongo

- [stream.uhi.ac.uk](https://stream.uhi.ac.uk)

- Online access to Data Science Tools

]

???
We already have expertise in remote teaching and tools to do so. Brightspace, Bongo, Video conferencing all allow for teaching of many different types of subjects and stream.uhi.ac.uk has already allowed me to begin flipping the classroom when teaching computational material. However, for something like a MSc students will probably need online access to data science tools to complete the computational work.

---
# Existing Web Technologies

.left-column[
### Why?

### What?

### How?
]

.right-column[
- Brightspace

- Video Conferencing

- Bongo

- <a href = "https://stream.uhi.ac.uk", target = "_blank">stream.uhi.ac.uk</a>

- Online access to Data Science Tools

- RStudio server

- Interactive tutorials/apps

]

???
Two examples are RStudio server which allows software to be accessed through a browser with no need for students to install anything. This can be extended with interactive tutorials than can also be run in a browser.

I have a couple of examples here to show you. 

---
# Existing Web Technologies

.left-column[
### Why?

### What?

### How?
]

.right-column[
- Brightspace

- Video Conferencing

- Bongo

- <a href = "https://stream.uhi.ac.uk", target = "_blank">stream.uhi.ac.uk</a>

- Online access to Data Science Tools

- RStudio server

- Interactive tutorials/apps

- <a href = "https://rstudio.cloud" target = "_blank">RStudio Cloud</a>

- <a href = "https://education.github.com" target = "_blank">Github Education</a>

]

???
There are many other things that could be used, for example RStudio cloud (currently in beta and free) which allows lecturers to predefine projects for students to work on - again in a browser and github allows institutions to set up academic accounts (free of charge) for students and lecturers to collaborate and work together, whilst the students learn how to use version control.
---
# In Conclusion

- Data Science important for rural workers.

- Scottish Government identified a need.

- Training possibly difficult to get to.

- Teaching computational skills using existing technologies.

???
So in summary data science skills are and will continue to be important for rural workers and the Scottish Government have identified a need to help rural businesses up skill in digital technologies. 

Training is possibly difficult to get to and so remote teaching may be critical and for this we can still teach computational skills using existing web technologies or open source tools.

---
class: inverse, center, middle

# Thanks for Listening

## Any Questions?
