---
title: "The Onion Method for Rearranging Equations"
date: "2017-11-19"
slug: "the-onion-method"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE,
                      warning = FALSE, comment = NA)
```

The other day in the office we were discussing methods of explaining how to change the subject of a formula, our different approaches and any alternatives we have. One difficulty that students can have is the order in which to rearrange and one of my colleagues demonstrated the *onion method* which I think might help some students. Below I outline how the method works with a couple of examples. 

## Example 1

If we take an example of the equation of motion below, where we want to change the subject to $t$. 

$$
\require{enclose}
v = u + at
$$
The onion method starts by drawing a circle around the new subject.
$$v = u + a\enclose{circle}{\:t\:}.$$

Then we circle the term closest to it

$$v =  u + \enclose{circle}{\:a\:\enclose{circle}{\:t\:}\:}$$

and continue with this until all the terms are circled

$$v = \enclose{circle}{\:u + \enclose{circle}{\:a\:\enclose{circle}{\:t\:}\:}\:}.$$

To rearrange we *peel away the layers*, so we start with the largest circle.

$$
\begin{align}
v &= \enclose{circle}{\:u + \enclose{circle}{\:a\:\enclose{circle}{\:t\:}\:}\:}. \\ 
v - u &= \enclose{circle}{\:u - u + \enclose{circle}{\:a\:\enclose{circle}{\:t\:}\:}\:}\\
v - u &= \enclose{circle}{\:a\:\enclose{circle}{\:t\:}\:} 
\end{align}
$$

We continue with this approach

$$
\begin{align}
v - u &= \enclose{circle}{\:a\:\enclose{circle}{\:t\:}\:} \\
\frac{v - u}{a} &= \enclose{circle}{\:\frac{a\:\enclose{circle}{\:t\:}}{a}\:} \\
\frac{v - u}{a} &= \enclose{circle}{\:t\:} 
\end{align}
$$

In this case we are now finished 

$$
t = \frac{v - u}{a}
$$

but it works for more complicated examples too.

## Example 2

For a more complicated example we could use an equation that might model population growth and again change the subject to $t$.

$$P = P_0e^{kt}$$

As before we start by circling the new subject and then move outwards.

$$
\begin{align}
P &= P_0e^{k\enclose{circle}{\:t\:}} \\
P &= P_0e^{\enclose{circle}{\:k\enclose{circle}{\:t\:}\:}} \\
P &= P_0\enclose{circle}{\:\:\:e^{\enclose{circle}{\:k\enclose{circle}{\:t\:}\:}}\:} \\
P &= \enclose{circle}{\:P_0\enclose{circle}{\:\:\:e^{\enclose{circle}{\:k\enclose{circle}{\:t\:}\:}\:}\:}\:} 
\end{align}
$$

Having added our layers we can peel them away.

$$
\begin{align}
P &= \enclose{circle}{\:P_0\enclose{circle}{\:\:\:e^{\enclose{circle}{\:k\enclose{circle}{\:t\:}\:}\:}\:}\:} \\
(\div P_0) & \:\:\:\:\:\:\:\: (\div P_0) \\
\frac{P}{P_0} &= \enclose{circle}{\:\:\:e^{\enclose{circle}{\:k\enclose{circle}{\:t\:}\:}\:}\:}
\end{align}
$$

Remembering we use $\ln(x)$ to cancel $e^x$ give us the next step.

$$
\begin{align}
\ln\left(\frac{P}{P_0}\right) &= \ln \left( e^{\enclose{circle}{\:k\enclose{circle}{\:t\:}\:}\:} \right) \\
\ln\left(\frac{P}{P_0}\right) &= \enclose{circle}{\:k\enclose{circle}{\:t\:}\:} \\
\end{align}
$$

Finally, we can divide by $k$ and we have finished changing the subject to $t$.

$$
\begin{align}
\ln\left(\frac{P}{P_0}\right) &= \enclose{circle}{\:k\enclose{circle}{\:t\:}\:} \\
(\div k) &\:\:\:\:\:\ (\div k) \\
\frac{\ln\left(\frac{P}{P_0}\right)}{k} & = t \\
t & =\frac{\ln\left(\frac{P}{P_0}\right)}{k} \\
\end{align}
$$

