---
title: "Reflection on the Feedback Process Pt. 1"
date: "2017-10-21"
slug: "reflection-on-feedback-process-pt-1"
---

I've posted about the feedback I've asked for (and received) from students a [few][feedbacK_2017] [times][feedback_2016] [before][feedback_post] and the topic is frequently discussed in the workroom. 

After collecting the most recent set of feedback I took some time to reflect on the way I collect feedback from the students. As I normally do I spent some time searching for and reading published research/academic blog posts. A lot of the articles I found were about giving feedback to students after assessments and exams, rather than getting feedback from students. I was quite happy about this as it let me think about the whole feedback process. 

This blog post will reflect on getting feedback from students. In the next one I'll reflect on giving feedback to students. 

## Getting Feedback from Students

My current default method for gathering feedback (about my teaching) from students is a two step process. First, I divide the whiteboard into quarters and put four (sort of) questions up, leave the room and let the students answer them. The (sort of) questions are:

- What's good?

- What needs improved?

- More of ...?

- Less of ...?

I then follow this up with an individual (anonymous) quiz, either online or on paper. 

I've found leaving the room means the students are slightly more honest and the whiteboard means that I have no idea who has written what or how many students would give that feedback. This is why the follow up quiz, which I started after a discussion with a colleague led to the suggestion, has proven very useful - it allows me to get any feedback from those who didn't want to speak up in class and check how many people support the group feedback I got. 

Having done some reading a few themes came through. There is support for anonymity and for not being present when the feedback is given. In some examples other staff members took the feedback or it was done online. There is also support for general class discussion. Written feedback was ok but there was a concern that staff would recognise handwriting. 

The most interesting article I read was [this](https://www.cultofpedagogy.com/student-feedback/) one and I'll be coming back to that website. Two main things I took from this that I will be using as soon as I can. The first is to include a question like *Is there anything else I should know about this class?*. I thought this was a really interesting question, on first inspection it looks quite vague but I think it might produce some interesting responses. The second thing was the emphasis on class discussion. 

One of the things that I wonder about as an FE and HE lecturer is whether students think about what happens in their classes and whether they would prefer if things were done differently. I don't remember being asked about it at pretty much any point in my education. Of course that doesn't mean it didn't happen but I don't remember thinking about whether I could have been taught differently either. I hope that the process of feedback and involving students in the process both as a group and individuals encourages students to reflect on their education. 

At the moment I'll add that question to the end of my follow up quiz and try to involve the class in more discussion about the classroom. I'm sure I will reflect on this as we progress through the year. 


[feedback_2017]: https://aj2duncan.com/blog/feedback-term1-2017/
[feedback_2016]: https://aj2duncan.com/blog/feedback-term1-2016/
[feedback_post]:	https://aj2duncan.com/blog/feedback/