---
title:  "Feedback Term 1 2017-18"
date: "2017-10-17"
slug: "feedback-term1-2017"
---
As with [previous][feedback_2016] [years][feedback_post], I collected feedback at the end of the first term of teaching by putting up four questions I wanted answered on up on the whiteboard and then leaving the room. I will follow this up with a [Socrative][socrative] quiz to double check these things and collect any  individual feedback, in case someone didn't want to speak up in class.

Anyway here are the questions and the feedback. Any comments of mine are in _italics_.

### What's good?

- Structure of examples

- It's a balanced atmosphere

- Good attitude and helpful

- Andrew's adaptive explanations

### What needs improved?

- Nothing written here

### More of ...?

- Blackboard use _This is something I'm going to follow up_

- Examples

### Less of ...?

- Nothing written here

This year there was also an addition at the bottom of the board. First time this had happened but it was something I was very happy with. 

### Suggestions

- Document on blackboard with list of past paper questions by topic. _I have put up a link on Blackboard to an external site which has some of this information. I am having a think about whether there is something better I can do for the CfE exam papers_


[feedback_2016]: https://aj2duncan.com/blog/feedback-term1-2016/
[feedback_post]:	https://aj2duncan.com/blog/feedback/
[socrative]:		http://socrative.com/